# Generated by Django 3.2.16 on 2023-01-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_photo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
