# Generated by Django 3.2.16 on 2023-01-17 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_update_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='comment',
            name='no_of_comments',
            field=models.ManyToManyField(related_name='blog_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contributor_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='create',
            name='contributor_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delete',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='update',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update', to=settings.AUTH_USER_MODEL),
        ),
    ]
